pipeline {
    agent any

    environment {
        DEPLOY_DIR = "/opt/dev/apps/webapps/tdnv/ws-core"
        JAVA_HOME = '/usr/lib/jvm/java-21-openjdk-21.0.5.0.11-2.el9.x86_64'
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }
    
    tools {
        maven 'Maven 3.8.8'
        jdk 'JDK 21'
    }
    
    stages {
        stage('Check Java Version') {
            steps {
                sh 'java -version'
                sh 'mvn -version'
            }
        }

        stage('Add GitHub to known_hosts') {
            steps {
                sh 'mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts'
            }
        }

        stage('Checkout') {
            steps {
                git url: 'git@github.com:DaiTran02/tdnv-hanoi.git', credentialsId: 'github-sskey', branch: 'main'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('ws-core') {
                    sh 'mvn clean package -DskipTests -e'
                }
            }
        }
        
        
        
        
        stage('Deploy and Restart Service') {
            steps {
                script {
                    def artifactId = "ws-core"
                    def version = "0.0.1"
                    
                    def jarRelativePath = "ws-core/target/${artifactId}-${version}.jar"
                    
                    def absoluteJarPath = "${env.WORKSPACE}/${jarRelativePath}"

                    echo "Đường dẫn file JAR build được: ${absoluteJarPath}"

                    if (!fileExists(absoluteJarPath)) {
                        error("LỖI: Không tìm thấy file JAR tại ${absoluteJarPath}. Kiểm tra lại cấu hình build, artifactId, version và đường dẫn.")
                    }

                    sh "sudo /opt/dev/apps/webapps/tdnv/ws-core/deploy_ws_core.sh ${absoluteJarPath}"
                    
                    echo "Script deploy đã được gọi."
                }
            }
		}
    }
    
    
     post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline successfully completed.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
    
}
